### ISSUE TITLE
Bootstrap 5 is out

### ISSUE THREAD

**Issue by pamtbaau** [simplycomputing/grav-sc-bootstrap4#1]
Would it be an idea to use Bootstrap 5 instead of v4? 
- It saves a port later
- It has ditched jQuery

Update:
Looking at the code, I now realise that you didn't base it on Bootstrap v4 framework, but on the Bootstrap4 **theme**... Anyway, maybe this is a good time to port theme Bootstrap4 to Bootstrap5?

**Comment by simplycomputing** [comment]
Yes, I was working with an inheritance over an existing theme that I found in the Grav theme directory. I guess if the Grav team put out a Bootstrap5 theme I could change it over.

**Comment by simplycomputing** [comment]
I added the link to Grav's Bootstrap4 theme in the readme to make it clearer.
